# This is a comment
FROM resin/rpi-raspbian
MAINTAINER John Talton <johntalton@gmail.com>

RUN apt-get update

RUN apt-get install ntp
# COPY ntpd.conf /etc/ntpd.conf

# RUN apt-get install wget curl nano git-core ssh iproute2
# RUN apt-get install net-tools


# ntp
# 


# CMD [""]
CMD ["/bin/bash"]






