# This is a comment
# FROM resin/rpi-raspbian
# FROM arm32v7/debian
FROM armv7/armhf-debian
# FROM armhf/debian
MAINTAINER John Talton <johntalton@gmail.com>

RUN apt-get update

RUN apt-get -y install ntp xz-utils
# COPY ntpd.conf /etc/ntpd.conf

# RUN apt-get install wget curl nano git-core ssh iproute2
# RUN apt-get install net-tools


# ntp
# 


# CMD [""]
CMD ["/bin/bash"]






