# This is a comment
FROM jotalt/rpi-nodejs
MAINTAINER John Talton <johntalton@gmail.com>

RUN apt-get update

RUN apt-get -y install make g++ python
# RUN npm install -g i2c

# RUN apt-get uninstall make g++ python


CMD ["/bin/bash"]






